deploy:
  branch:
    server: docs.zen.ci
    username: backdrop
    dir: '{home}/github/{repo_owner}/{repo_name}/{branch}'
    env_vars:
      docroot: '{home}/domains/docs.zen.ci'
      database_name: backdrop_docs
      database_user: backdrop_docs
      database_pass: hjbhfwef67w
      account_user: admin
      account_mail: admin@zen.ci
      account_pass: changeme
      site_mail: noreply@zen.ci
      site_name: "Documentation site"
    scripts:
      init: '{deploy_dir}/install.sh'
